name: 'wiz-cli'
on:
  workflow_dispatch:

jobs:
  wiz-cli-iac-scan:
    name: 'Wiz-cli Directory Scan'
    runs-on: ubuntu-latest
    env:
      SCAN_PATH: "." # Set the relative path in the repo to scan

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Download Wiz CLI
      run: curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli

    - name: Authenticate to Wiz
      run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"
      env:
        WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
        WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
        WIZ_ENV: ${{ secrets.WIZ_ENV }}

    - name: Run wiz CLI Directory scan
      run: ./wizcli dir scan --output wizscan.sarif,sarif --path . 
      env:
        WIZ_ENV: ${{ secrets.WIZ_ENV }}

    - name: Validate file creation
      run: cat wizscan.sarif
